### ISSUE TITLE
Doesn't work with Logitech Momo wheel/pedals

### ISSUE THREAD

**Issue by djwhatle** [simonowen/dashfix#3]
Trying to use dashfix to cancel SteamVR input from my Logitech Momo wheels/pedals but so far haven't been successful. I still am unable to use the Vive controller to do anything in the SteamVR overlay while the Momo is connected. I hear very rapid "mouse-over" noises and see the button highlights scroll across the screen to the right the whole time.

So far I've tried:

- Launching dashfix while SteamVR is running
- Launching dashfix before launching SteamVR

More info:

 - Windows 10 (Creators Update Installed)
 - I have the latest Logitech Gaming Software from [link](http://support.logitech.com/en_us/product/momo-racing-force-feedback-wheel/downloads#windowsPnlBar) installed.

**Comment by simonowen** [comment]
The symptoms do sound typical for controller interference.

- Does DashFix show the Momo in its list of detected controllers on startup?
- Have you tried unchecking all controllers in the list?

I no longer have a Logitech wheel to debug it myself, but I could add some diagnostics if you're willing to test it?

**Comment by simonowen** [comment]
Did you find a solution for this issue?

**Comment by djwhatle** [comment]
No, but I moved on to another wheel at this point and can't provide any feedback on the Momo. 

Haven't been using the SteamVR overlay for anything while using the wheel now, so I am not using DashFix currently.
