### ISSUE TITLE
No Controllers Show Up

### ISSUE THREAD

**Issue by FolkSong** [simonowen/dashfix#5]
When I open DashFix the list of controllers is empty. I have a Logitech G27 and it shows up under USB Game Controllers.

**Comment by simonowen** [comment]
Is there anything else running that you think could have the controller open at the time?

Is the controller listed in Steam under Steam -> Settings -> Controller (bottom entry on left) -> General Controller Settings (button)?  My wheel shows up in the Detected controllers section at the bottom.

Do you own any other controllers that you can connect to see if they appear in DashFix?

If you're willing to run some additional tests I'll add some debug diagnostics...

**Comment by FolkSong** [comment]
I found that the wheel does not show up in the Steam detected controllers, and it's not active in Big Picture, but in SteamVR I get the constant scrolling and can't select anything.

I can test with a game pad but given the above I'm pretty sure it would show up normally in DashFix. This sounds like a SteamVR bug more than anything.

The only other software that talks to the wheel is the Logitech Profiler, but everyone would have that.

**Comment by FolkSong** [comment]
Oddly enough, I tried re-installing DashFix and this time the wheel showed up. Now the software is working perfectly for me.

In case it helps anyone else, here is what I can think of that I did differently:
1. I had recently unplugged and re-plugged my wheel into USB
2. I had an Xbox One controller connected at the same time
3. Uninstalled and reinstalled DashFix

**Comment by simonowen** [comment]
Thanks for the update, and glad to hear it's fixed now!  I was away over the weekend so I hadn't got round to looking at the issue yet.

Does the wheel now also show up in Steam?  We 're using the same SDL2 library for the list, and I can't think why it wouldn't be able to see it when it's connected.  I'll look into it in case there's something that can be done to help.
